files:
  - index.html
  - main.js
  - math.js
  - helper.js
  - matrix.js
  - gl-utils.js
  # - gl-data.js
  # - style.css

ask_overwrite: false
output: result.txt
add_file_names: true
file_label: "Файл: "
