files:
  - index.html
  - js/main.js
  - js/math.js
  - js/helper.js
  - js/matrix4.js
  - js/matrix5.js
  - js/gl/utils.js
  # - js/gl-data.js
  # - style/style.css

add_file_names: true
code_in_md: true
file_label: "Файл: "
output: result.txt
