files:
  - index.html
  - js/main.js
  - js/math/constants.js
  - js/math/coordinates.js
  # - js/matrix/4.js
  - js/matrix/5.js
  - js/helpers/document.js
  - js/helpers/error.js
  - js/gl/utils.js
  - js/shaders/fragment.glsl
  - js/shaders/vertex.glsl
  - js/shaders/getShader.js
  - js/gl/data.js
  # - style/style.css

add_file_names: true
code_in_md: true
file_label: "Файл: "
output: result.txt
